name: Bug Report / Feature Request
description: 报告模板中的问题或者请求实现更多功能。

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: 提交前检查
      description: 请确保你提交的问题符合以下的要求。
      options:
        - label: 我已经充分阅读了模板文档。
          required: true
        - label: 我的问题并非关于模板的用法（否则请前往 discussions 提出）。
          required: true
        - label: 我已经搜索了已有的 issues 和 discussion，确认没有重复提交。
          required: true

  - type: input
    id: system
    attributes:
      label: 系统
      description: 使用的系统
      placeholder: macOS 13.2 / Windows 11 / Ubuntu 24.04 / Overleaf / TeXPage
    validations:
      required: true

  - type: input
    id: tex-distro
    attributes:
      label: TeX 发行版
      description: 使用的 TeX 发行版（在线平台可在项目设置中查看）
      placeholder: TeX Live 2024 / MiKTeX 24.1 / CTEX 3.0.216.3
    validations:
      required: true

  - type: input
    id: tex-program
    attributes:
      label: TeX 编译器
      description: 使用的 TeX 程序（如不了解，保留默认值）
      placeholder: XeLaTeX / LuaLaTeX / pdfLaTeX
      value: XeLaTeX
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 版本
      description: 使用的模板版本（可打开 `thuthesis.cls` 搜索 `\ProvidesClass` 查看）
      placeholder: '7.4.0'
    validations:
      required: true

  - type: dropdown
    id: degree-type
    attributes:
      label: 学位类型
      description: 模板的学位论文类型
      options:
        - bachelor
        - master
        - doctor
        - postdoc
    validations:
      required: true

  - type: textarea
    id: bug-report
    attributes:
      label: 问题描述
      description: 请简要描述你遇到的问题，并附上必要的截图等。
      placeholder: |
        《研究生学位论文写作指南》第 xx 页要求……
        而模板编译的结果是……
    validations:
      required: true

  - type: textarea
    id: reproducer
    attributes:
      label: 复现代码
      description: 能复现上述问题的最小代码片段
      render: TeX
      placeholder: |
        \documentclass[degree=doctor]{thuthesis}
        \begin{document}
        abc
        \end{document}
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: 编译日志
      description: 相关的编译日志（文本形式粘贴）
      render: Text

  - type: textarea
    id: additional-info
    attributes:
      label: 其他信息
      description: 其他你认为有必要提供的信息
