blank_issues_enabled: true
contact_links:
  - name: 模板文档
    url: http://mirrors.ctan.org/macros/latex/contrib/thuthesis/thuthesis.pdf
    about: 阅读模板使用文档。
  - name: GitHub Discussions
    url: https://github.com/tuna/thuthesis/discussions
    about: 在讨论区询问模板的使用方法。
